services:
  client:
    container_name: client
    build:
      context: ./real-time-online-chats.Client
      dockerfile: Dockerfile.client
    ports:
      - "5173:5173"
      - "5174:5174"
    environment:
      NODE_ENV: development
    depends_on:
      - api
  api:
    container_name: api
    build:
      context: ./real-time-online-chats.Api
      dockerfile: Dockerfile.api
    env_file:
      - ./real-time-online-chats.Api/src/WebAPI/.env
    restart: always
    ports:
      - "5039:5039"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5039
      - DB_HOST=api.postgres
      - REDIS_HOST=redis
    depends_on:
      - api.postgres
      - redis

  api.postgres:
    image: postgres:16.9-alpine
    container_name: api.postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "roc_db"

  redis:
    image: redis:8.0.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
