services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - api.postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - DB_HOST=api.postgres

  api.postgres:
    image: postgres:latest
    container_name: api.postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "roc_db"
    ports:
      - "5433:5432"