FROM node:20-alpine

WORKDIR /client
COPY package.json .
COPY tsconfig.json .
COPY tsconfig.app.json .
COPY tsconfig.node.json .

RUN npm install

COPY . .

RUN npm run build

EXPOSE 5173
EXPOSE 5174

CMD [ "npm", "run", "dev" ]
